### ISSUE TITLE
 Feature Request: Add "Forgot Password" Feature to Login Page

### ISSUE THREAD

**Issue by kaali001** [dvjsharma/Drawn2Shoe#144]
### **Describe the new feature**
The login page currently lacks a "Forgot Password" feature, which is essential for users who have forgotten their passwords and need a way to reset them. Implementing this feature will enhance user experience by providing an easy and secure method for users to regain access to their accounts.

### **Describe the possible approach**
**Frontend:**

- Add a "Forgot Password?" link to the login page.
- Create a password reset form where users can enter their email address.
- Design a password reset page where users can enter and confirm a new password.

**Backend:**

- Add endpoints to handle password reset requests, send verification emails, and update passwords.
- Implement secure token generation and validation for the password reset process.

### **Describe any alternatives**

- **Security Questions:** Instead of sending a password reset link via email, users could answer security questions to reset their passwords. However, this method is generally considered less secure and user-friendly compared to email-based password reset.

- **Two-Factor Authentication (2FA):** Implementing 2FA as an alternative way to recover accounts could add an extra layer of security, but it requires users to set up 2FA in advance and might be more complex to implement initially.

**Comment by kaali001** [comment]
Hey @dvjsharma , I would like to work on this feature assign it to me.

**Comment by dvjsharma** [comment]
I think the general approach would be good, we can integrate services like nodemailer to send the password reset link and the instructions can follow. Also, if we want to increase the scope of this PR, we may outsource the entire user handling part to an external package with inbuilt basic functionalities. 

As of now, I am holding this ticket since you have many tickets assigned under your name. We'll get back to you once you are a bit less occupied.
Thanks.

**Comment by dvjsharma** [comment]
You can work on this @kaali001.

**Comment by dvjsharma** [comment]
Closing against #151
